---
title: "Zebrafish: pyrene exposure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read, message=FALSE}
## read libraries and data
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(ComplexHeatmap)
library(ggprism)
library(ggplotify)
library(cowplot)
library(readxl)
library(openxlsx)
library(svglite)
library(edgeR)
library(WGCNA)

HTSeq <- read.csv("./Data/htseq_zebra_pyrene.tsv",sep="\t",header=TRUE,row.names=1,stringsAsFactors=F)
dim(HTSeq)
# [1] 49290  60

## Input 
Concentration <-  c(rep(0,15),rep(15,15),rep(60,15),rep(240,15)) 
```




## edgeR analysis
```{r edgeR_fullmodel}
expression <-  HTSeq[- c( (nrow(HTSeq)-4):nrow(HTSeq)),] %>% 
    mutate_if (is.character,as.numeric)

tail(expression)[,1:5]
#  note: should be checked the proportion of "no feature" and "not aligned" and so on



################## Grouping & Normalization ###########################
Conc_factor <-  Concentration %>% as.factor() 
Design <- model.matrix(~0+Conc_factor)


exp_res <- DGEList(counts= expression, genes=rownames(expression))
dim(exp_res)
# [1] 49285    60
 
# check lib size
barplot(exp_res$samples$lib.size,names=colnames(exp_res),las=2,cex.names=0.7)
abline(h=median(exp_res$samples$lib.size),col="chocolate",lty="dotted",lwd=2)

# Remove genes with low expression levels
keep <- rowSums(cpm(exp_res) > 10) >= 10    #Count > 10 out of 10 libraries
table(keep)  
#note: Averaged library size is 17 M. Chen et al (2016, F1000) recommends that a gene should have a count of at least 10–15 in at least some libraries. 
#keep
# FALSE  TRUE 
# 35796 13489     TRUE: retaining genes
exp_res_filtered <- exp_res[keep, , keep.lib.sizes=FALSE] 
exp_res_filtered <- calcNormFactors(exp_res_filtered)  # perform TMM normalization
dim(exp_res_filtered)
# [1] 13489    60

# check the counts distribution
par (mar=c(1,3,6,1),mfrow=c(2,1) )
boxplot(cpm(exp_res,log=TRUE),las=2,cex.axis=1,names=FALSE,ylab="logCPM")
title("before normalization")
par (mar=c(6,3,1,1))
boxplot(cpm(exp_res_filtered,log=TRUE),las=2,cex.axis=1,ylab="logCPM")
title("after normalization")


#plotMDS 
MDS <- plotMDS(exp_res_filtered,top = 2000, plot=FALSE )  #top indicates number of used genes 
MDS <- data.frame(X=MDS$x,Y=MDS$y, Conc=Conc_factor, ID=row.names(MDS$"distance.matrix.squared")  ) %>%
  mutate(Conc= factor(Conc,levels=c("Control","Low","Middle","High"))) 
 
MDS_plot <- ggplot(MDS, aes(x=X,y=Y, label=Conc_factor,shape=Conc_factor,col=Conc_factor))+
     geom_point(size=4,alpha=0.7,stroke=1.1)+
     geom_text_repel(aes(x=X,y=Y,label=Conc_factor))+
     theme_bw(base_size=25) +
     theme(strip.background = element_blank(),panel.grid = element_blank(),legend.position = "none")+
     scale_shape_manual(values=c(19, 21, 22, 4))+
     scale_color_manual(values=c("grey","#E69F00","#56B4E9","#009E73"))

#svglite("Figure_MDSplot_20250718.svg", width=7, height=6)
#MDS_plot
#dev.off()




#plotMD (Mean-Difference)
par (mfrow=c(1,1) )
plotMD(exp_res_filtered,column=1)  #column indicates the number of sample
abline(col="red",h=0)

# design matrix
# Estimate dispersion
exp_res_design <- estimateDisp(exp_res_filtered, Design, robust=TRUE)
exp_res_design$common.dispersion
# [1] 0.004793607
# The square root of the common dispersion gives the coefficient of variation of biological variation. Here the common dispersion is found to be  0.004793607, so the coefficient of biological variation is around 0.0687.

plotBCV(exp_res_design)
# For RNA-seq studies, the NB dispersions tend to be higher for genes with very low counts (Chen et al. 2016, F1000).


# Fit to model
fit <- glmQLFit(exp_res_design, Design, robust=TRUE)  # estimation of Quarsi-Likelihood dispersions 
head(fit$coefficients)
plotQLDisp(fit)




logCPM <- rbind(Dose= Concentration, cpm(exp_res_design, prior.count=2, log=TRUE) )
dim(logCPM)
#[1] 13490    60
write.csv(logCPM %>% data.frame,"logCPM.csv")  
  
## this csv file will be analyzed by BMDExpress


```






## WGCNA 
```{r WGCNA}
#### Making expression table
## Genes without concentration-responses were filtered out by ANOVA in WGCNA 
## Following BMDExpress, genes will be clustered by WGCNA
data <- read_delim("./Data/logCPM_forBMDExpress_oneway_0.05_MTC_nofoldfilter_BMD_pyrene.txt",
                  ,skip = 43  ) 
dim(data)
# [1] 10116   157


## filter out genes without fitted model
data2 <- data %>% data.frame() %>%
  dplyr::filter(.$"Best.Model" != "none")
dim(data2)
# [1] 10092   157




# Retrieve genes from expression table
logCPM <- logCPM %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  filter(gene %in% data2$"Probe.ID") %>%
  column_to_rownames(var="gene") %>% as.matrix

dim(logCPM)
# [1] 10092    60



######    WGCNA   #######
## Appropriate Power to Use for the correlation coefficient
datExpr <- t(logCPM)  # For WGCNA, row: sample, column: gene
WGCNA::allowWGCNAThreads()
powers <- c(seq(1,10,1), seq(12,30,2))
sft <- WGCNA::pickSoftThreshold(datExpr,
                                powerVector = powers,
                                networkType = "signed",
                                verbose = 5)

# scale-free topology fit index
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"))
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,col="red")

# Determination of Power     （Minimum power satisfying Scale free topology ≥0.8. If not, power should be 12.）
sf_ok <- which(sft$fitIndices[,2] >= 0.8)
softPower <- if(length(sf_ok)) sft$fitIndices[min(sf_ok),1] else 12
message(sprintf("Chosen softPower = %s", softPower))
# Chosen softPower = 8




#### WGCNA: Module estimation ####
cor=WGCNA::cor
net <- WGCNA::blockwiseModules(
  datExpr,
  power = softPower,
  networkType = "signed",  #directional
  TOMType = "signed",
  corType = "pearson",
  corFnc  = "cor",                              
  corOptions = list(use = "pairwise.complete.obs", method = "pearson"),
  minModuleSize = 50,　   　#default: 20
  reassignThreshold = 0, 
  mergeCutHeight = 0.35,     #default: 0.15
  deepSplit = 0,　　        #default: 2
  numericLabels = TRUE,
  saveTOMs = FALSE,
  verbose = 3
)

moduleColors <- WGCNA::labels2colors(net$colors)
moduleColors  %>% unique() %>% length()
# [1] 9   
# note: No. of modules is 6 .... minModuleSize 100, mergeCutHeight 0.4, deepSplit = 0 
# note: No. of modules is 9 ....minModuleSize 50, mergeCutHeight  0.35, deepSplit = 0 
#### The number of modules may vary depending on the version of R or WGCNA.

MEs0 <- WGCNA::moduleEigengenes(datExpr, colors = moduleColors, softPower = softPower)$eigengenes
MEs  <- data.frame( Concentration = Concentration) %>% cbind( WGCNA::orderMEs(MEs0)) %>%
  remove_rownames()
  

write.csv(MEs,"logCPM_eigengenes_pyrene_9modules.csv", row.names = FALSE)   ### Inout data for python lingam analysis



#　Gene composition in each module
WGCNA::plotDendroAndColors(
  net$dendrograms[[1]],
  moduleColors[net$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05 )

module_df <- data.frame(
  gene_id = names(net$colors),
  colors = moduleColors
)

head(module_df)


genes_to_check <- c("ahr2","arnt2","sox9b","COX2","vegfab") 
module_df %>% filter(gene_id %in% genes_to_check)
#  gene_id    colors
#1    COX2      blue
#2    ahr2      blue
#3   arnt2     brown
#4   sox9b      blue
#5  vegfab turquoise
  
module_df %>% group_by(colors) %>% summarize(Number =n()) 
#  colors    Number
#1 black        290
#2 blue        2145
#3 brown       1488
#4 green        614
#5 grey         627
#6 pink         275
#7 red          348
#8 turquoise   3672
#9 yellow       632




####### Integrate the BMDExpress result into WGCNA ######
data_BMD <- data2 %>% 
  dplyr::select(c("Probe.ID","Best.BMD","Best.BMDL","Best.BMDU","Best.fitPValue"))

module_df <- module_df %>%
  mutate(BMDL = as.numeric(data_BMD[match(.$"gene_id",data_BMD$"Probe.ID",),"Best.BMDL"] )) %>%
  mutate(BMD = as.numeric(data_BMD[match(.$"gene_id",data_BMD$"Probe.ID",),"Best.BMD"] )) 
dim(module_df)
# [1] 10092   4
# write.csv(module_df, "module_df_9modules.csv")

module_df$BMD %>% hist()

# summary of BMD values in each module
module_df %>% 
  group_by(colors) %>%
  summarize(Mean_BMDL =mean(BMDL), Median_BMDL =median(BMDL), SD_BMDL =sd(BMDL),
            Mean_BMD =mean(BMD), Median_BMD =median(BMD), SD_BMD =sd(BMD)  )
#  colors    Mean_BMDL Median_BMDL SD_BMDL Mean_BMD Median_BMD SD_BMD 
#1 black         179.        214.    134.     2851.      250.   6831.   
#2 blue           44.3        17.1    64.7     291.       50.4  2498.  
#3 brown          52.2        14.6    96.0     945.       42.2  9297.  
#4 green         117.        128.     69.3     338.      201.   1930.  
#5 grey          174.        159.    363.     4783.      249.  59848. 
#6 pink          163.        198.    107.     1928.      245.   5889. 
#7 red           115.        112.     65.5     526.      181.   2845.  
#8 turquoise      40.0        15.9    63.2     380.       41.1  6666. 
#9 yellow        167.        187.    126.     2540.      246.   9669.  




```

